import { model, Schema, type Types } from "mongoose";

import { type BookingCurrency, bookingCurrencies } from "../booking/booking.types.js";

/**
 * A real bank-transfer batch to a Business (Batch 7 introduced this model with no write path;
 * Batch 8 activates it). Deliberately a SEPARATE entity from BookingFinancialTransaction rather
 * than reusing its `BUSINESS_PAYOUT` type: that ledger type is scoped to one `bookingId`
 * (required on the schema), which cannot represent "one payout covering many bookings/
 * transactions accumulated over time" without either faking a bookingId or loosening the
 * ledger's own required field — neither acceptable (see booking-financial-transaction.model.ts's
 * own "never Mongoose directly"/immutability doc comments). This collection is the payout-level
 * aggregate; the ledger remains the line-item source of truth those totals are computed from.
 *
 * BATCH 8 — MANUAL, SELF-ATTESTED PAYOUT (confirmed product decision, not inferred): no real
 * SEPA/Stripe Connect transfer-EXECUTION infrastructure exists in this codebase. A payout row is
 * created ONLY by BusinessPayoutService.executePayout, when a Super Admin clicks "Send SEPA" /
 * "Confirm Transfer" in the Super Admin Finance UI — this is the Super Admin ATTESTING they have
 * already sent (or are about to send) this exact net amount to the Business via their own bank/
 * Stripe dashboard OUTSIDE Bookly, mirroring the already-established `BookingCompletionPayment`
 * self-attestation pattern (Batch 5 — "a Business self-attestation about money collected
 * OFF-platform... Bookly has no way to independently verify it"). A row is therefore written
 * DIRECTLY as `status: "PAID"`, `paidAt: <now>` in one step — never as an intermediate "sent but
 * unconfirmed" state, since there is no external system to later confirm it against. `PENDING`
 * remains in the status enum only for schema forward-compatibility with a genuine future
 * transfer-execution integration; nothing in this batch ever writes it.
 *
 * `settledTransactionIds` is the explicit, auditable linkage this payout settles (rule #12) —
 * every one of those ledger rows also carries this payout's own `_id` back on its own
 * `payoutId` field (see booking-financial-transaction.model.ts) — bidirectional, purely for
 * cheap lookups either direction; the ledger's `payoutId` field (set exactly once, inside the
 * same transaction as this document's insert) is the actual source of truth preventing a
 * transaction from ever being paid out twice, not this array alone.
 */
export type BusinessPayoutStatus = "PENDING" | "PAID";
export const businessPayoutStatuses = ["PENDING", "PAID"] as const;

export type BusinessPayoutDocument = {
  _id: Types.ObjectId;
  businessId: Types.ObjectId;
  /** [periodStart, periodEnd] — the min/max `createdAt` of the settled transactions, NOT an
   * artificial calendar-month boundary (a payout can be triggered at any time, covering
   * whatever accumulated since the last one — rule #9: "no automatic daily/weekly/monthly
   * payout"). Purely descriptive/display; never used to decide payout eligibility. */
  periodStart: Date;
  periodEnd: Date;
  /** The Business-owned amount this payout settles, before processing-fee/refund deduction. */
  grossBusinessOwnedCents: number;
  /** Business-borne Stripe processing fees deducted from `grossBusinessOwnedCents` — the real,
   * actual-Stripe-data amount (never an estimate; see finance-ownership.ts). */
  processingFeesCents: number;
  /** Business-owned refund reversals (e.g. a returning customer's DEPOSIT refunded on a
   * Business-initiated cancellation) deducted from `grossBusinessOwnedCents` — kept as its own
   * field rather than folded into `processingFeesCents` so a refund is never misrepresented as
   * a processing cost (rule #23 auditability). */
  refundsCents: number;
  /** grossBusinessOwnedCents - processingFeesCents - refundsCents — the amount the Super Admin
   * is attesting they transferred. */
  netPayoutCents: number;
  currency: BookingCurrency;
  status: BusinessPayoutStatus;
  /** The exact BookingFinancialTransaction rows this payout settles — see this type's own doc
   * comment on the bidirectional linkage. */
  settledTransactionIds: Types.ObjectId[];
  /** Which Super Admin attested/triggered this payout — required (this batch's flow always sets
   * it; there is no automated payout path). */
  initiatedByUserId: Types.ObjectId;
  /** An optional REAL bank/transfer reference the Super Admin may type in as their own evidence
   * (e.g. their bank's confirmation code) — never auto-generated by Bookly, since Bookly has no
   * real transfer integration to generate one from (rule #11: never fabricate a transfer
   * reference). */
  providerReference?: string | undefined;
  paidAt?: Date | undefined;
  createdAt: Date;
  updatedAt: Date;
};

const businessPayoutSchema = new Schema<BusinessPayoutDocument>(
  {
    businessId: { type: Schema.Types.ObjectId, ref: "Business", required: true },
    periodStart: { type: Date, required: true },
    periodEnd: { type: Date, required: true },
    grossBusinessOwnedCents: { type: Number, required: true, min: 0, validate: Number.isInteger },
    processingFeesCents: { type: Number, required: true, min: 0, validate: Number.isInteger },
    refundsCents: { type: Number, required: true, min: 0, validate: Number.isInteger },
    netPayoutCents: { type: Number, required: true, min: 0, validate: Number.isInteger },
    currency: { type: String, enum: bookingCurrencies, required: true, default: "EUR" },
    status: { type: String, enum: businessPayoutStatuses, required: true, default: "PENDING" },
    settledTransactionIds: {
      type: [{ type: Schema.Types.ObjectId, ref: "BookingFinancialTransaction" }],
      required: true,
      validate: {
        validator: (value: unknown[]) => value.length > 0,
        message: "A payout must settle at least one transaction",
      },
    },
    initiatedByUserId: { type: Schema.Types.ObjectId, ref: "User", required: true },
    providerReference: { type: String, trim: true },
    paidAt: { type: Date },
  },
  { timestamps: true },
);

// Payout history for a Business, most recent period first — the one read pattern this
// collection serves for a single Business.
businessPayoutSchema.index({ businessId: 1, periodStart: -1 });
// Super Admin's platform-wide payout history / "sent to businesses" totals — no businessId
// filter, ordered by recency.
businessPayoutSchema.index({ status: 1, createdAt: -1 });

export const BusinessPayoutModel = model<BusinessPayoutDocument>(
  "BusinessPayout",
  businessPayoutSchema,
);
